#include <absl/base/log_severity.h>
#include <absl/flags/flag.h>
#include <absl/flags/marshalling.h>
#include <absl/flags/parse.h>
#include <absl/flags/usage.h>
#include <absl/log/check.h>
#include <absl/log/log.h>
#include <absl/strings/string_view.h>
#include <fmt/format.h>
#include <grpcpp/ext/proto_server_reflection_plugin.h>
#include <grpcpp/grpcpp.h>
#include <onnxruntime_cxx_api.h>

#include <fstream>
#include <iostream>
#include <memory>
#include <string>
#include <thread>

struct PortNumber {
  explicit PortNumber(int p = 0) : port(p) {}

  int port;  // Valid range is [0..65535]
};

// Returns a textual flag value corresponding to the PortNumber `p`.
std::string AbslUnparseFlag(PortNumber p) {
  // Delegate to the usual unparsing for int.
  return absl::UnparseFlag(p.port);
}

// Parses a PortNumber from the command line flag value `text`.
// Returns true and sets `*p` on success; returns false and sets `*error`
// on failure.
bool AbslParseFlag(absl::string_view text, PortNumber* p, std::string* error) {
  // Convert from text to int using the int-flag parser.
  if (!absl::ParseFlag(text, &p->port, error)) {
    return false;
  }
  if (p->port < 0 || p->port > 65535) {
    *error = "not in range [0,65535]";
    return false;
  }
  return true;
}

struct RequiredFile {
  explicit RequiredFile(std::string s = "") : path(s) {}

  std::string path;
};

std::string AbslUnparseFlag(RequiredFile s) {
  return absl::UnparseFlag(s.path);
}

bool AbslParseFlag(absl::string_view text, RequiredFile* s,
                   std::string* error) {
  if (!absl::ParseFlag(text, &s->path, error)) {
    return false;
  }
  if (s->path.empty()) {
    *error = "option is required but missing";
    return false;
  }
  if (!std::ifstream(s->path)) {
    *error = fmt::format("File at '{}' does not exist", s->path);
    return false;
  }
  return true;
}

#include "inference/inference.grpc.pb.h"  // Generated by protobuf compiler: protoc -I . --cpp_out=. --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` inference.proto

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::Status;
using inference::Runtime;
using inference::SessionRequest;
using inference::SessionResponse;

ABSL_FLAG(absl::optional<RequiredFile>, model_path, absl::nullopt,
          "Path to ONNX model");
ABSL_FLAG(absl::LogSeverity, log_level, absl::LogSeverity::kInfo,
          "Logging level. Allowed options (case sensitive): info, warning, "
          "error, fatal");
ABSL_FLAG(std::string, address, "0.0.0.0", "The base server address");
ABSL_FLAG(int, num_threads, 0, "Number of server threads");
ABSL_FLAG(PortNumber, grpc_port, PortNumber(50051),
          "GRPC port to listen to requests");

// Service implementation
class RuntimeImpl final : public Runtime::Service {
  std::string model_path_;  // Private class member for model_path
  std::string model_content_;

 public:
  RuntimeImpl(const std::string& model_path) : model_path_(model_path) {
    std::ifstream file(model_path);
    if (!file) {
      throw std::runtime_error("File does not exist");
    }
    std::string content((std::istreambuf_iterator<char>(file)),
                        std::istreambuf_iterator<char>());
    this->model_content_ = content;
  }

  Status Run(ServerContext* context, const SessionRequest* request,
             SessionResponse* reply) override {
    for (const auto& tuple : request->array_map()) {
      std::cout << "Tuple name: " << tuple.name() << std::endl;
      std::cout << "Length of values: " << tuple.values_size() << std::endl;
      reply->mutable_array_map()->Add()->CopyFrom(tuple);
    }
    return Status::OK;
  }
};

void RunServer(const std::string& address, const int port,
               const int num_threads, const std::string& model_path) {
  std::string server_address = fmt::format("{}:{}", address, port);
  grpc::EnableDefaultHealthCheckService(true);
  grpc::reflection::InitProtoReflectionServerBuilderPlugin();

  RuntimeImpl service(model_path);

  grpc::EnableDefaultHealthCheckService(true);
  grpc::reflection::InitProtoReflectionServerBuilderPlugin();
  ServerBuilder builder;
  builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
  builder.RegisterService(&service);
  grpc::ResourceQuota quota;
  quota.SetMaxThreads(num_threads);
  builder.SetResourceQuota(quota);

  std::unique_ptr<Server> server(builder.BuildAndStart());
  std::cout << fmt::format("Server listening on {}:{}", server_address, port)
            << std::endl;

  server->Wait();
}

int main(int argc, char** argv) {
  absl::SetProgramUsageMessage("./onnxruntime_server --model_path trained.pt");
  absl::ParseCommandLine(argc, argv);
  QCHECK(absl::GetFlag(FLAGS_model_path).has_value())
      << "the option '--model_path' is required but missing";

  const std::string server_address =
      absl::GetFlag(FLAGS_address);  // Get server address using absl flag
  const PortNumber port_number =
      absl::GetFlag(FLAGS_grpc_port);  // Get port value using absl flag
  const std::string model_path = absl::GetFlag(FLAGS_model_path).value().path;

  int num_threads = absl::GetFlag(FLAGS_num_threads);
  if (num_threads == 0) {
    num_threads = std::thread::hardware_concurrency();
  }
  RunServer(server_address, port_number.port, num_threads, model_path);
  return 0;
}
